#!/bin/bash

gcc -Wall -pedantic main.c -lm -o output.out
PROG="output.out"

if [ -n $1 -a $1 != " " ]
then
    QUERY="tests/$1_in.txt"
else
    QUERY="tests/????_in.txt"
fi

for INPUT in $QUERY
do
    INPUT_FILENAME=`basename $INPUT` &&
    OUTPUT_FILE=tests/${INPUT_FILENAME:0:4}_out.txt

    ./$PROG < $INPUT > output.txt

    TEST=$(diff $OUTPUT_FILE output.txt)
    if [ $? -eq 0 ]
    then
        tput setaf 2
        tput bold
        echo "${INPUT_FILENAME:0:4}: Success"
        tput sgr0
    else
        tput setaf 1
        tput bold
        echo -e "${INPUT_FILENAME:0:4}: Failed"
        tput sgr0
        tput bold
        echo "For input:"
        tput sgr0
        echo -e "$( cat $INPUT )\n"
        tput bold
        echo "Error in:"
        tput sgr0
        echo -e "$TEST\n"
    fi
done
