#!/bin/bash

gcc -Wall -Werror -pedantic main.c -lm -o output.out
if [ $? -eq 1 ]
then
    exit
fi

PROG="output.out"
QUERY="tests/????_in.txt"

if [ $# -ne 0 ]
then
    QUERY=""
    for ARG in $@
    do
        if [ $ARG -lt 10 ]
        then
            ARG="000$ARG"
        elif [ $ARG -lt 100 ]
        then
            ARG="00$ARG"
        elif [ $ARG -lt 1000 ]
        then
            ARG="0$ARG"
        fi

        QUERY="$QUERY"" ""tests/""$ARG""_in.txt"
    done
fi

for INPUT in $QUERY
do
    INPUT_FILENAME=`basename $INPUT` &&
    OUTPUT_FILE=tests/${INPUT_FILENAME:0:4}_out.txt

    if [ -f $INPUT ]
    then
        O=$( ./$PROG < $INPUT )

        TEST=$(diff -y --color=always $OUTPUT_FILE <( echo "$O" ))
        if [ $? -eq 0 ]
        then
            tput setaf 2
            tput bold
            echo "${INPUT_FILENAME:0:4}: Success"
            tput sgr0
        else
            tput setaf 1
            tput bold
            echo -e "${INPUT_FILENAME:0:4}: Failed"
            tput sgr0
            tput bold
            echo "Input:"
            tput sgr0
            echo -e "$( cat $INPUT )\n"
            tput bold
            echo "Error in:"
            tput sgr0
            echo -e "$TEST\n"
        fi
    else
        tput setaf 1
        tput bold
        echo "${INPUT_FILENAME}: Missing input file"
        tput sgr0
    fi
done
